name: Auto Merge Branches with Date Differences

on:
  workflow_dispatch:
  push:
    branches:
      - 'profit_dep_hf_*'
      - 'profit_dep_minor_*'

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch All Remote Branches
        run: |
          git fetch --all
          echo "Remote branches:"
          git branch -r

      - name: Determine Latest HF and Corresponding Minor Branch
        id: determine-branches
        run: |
          # Fetch list of remote branches
          REMOTE_BRANCHES=$(git branch -r)
          
          # Find the latest HF branch
          LATEST_HF_BRANCH=$(echo "$REMOTE_BRANCHES" | grep 'origin/profit_dep_hf_' | sort -V | tail -n 1 | sed 's/origin\///')
          
          # Extract date suffix from HF branch
          DATE_SUFFIX=${LATEST_HF_BRANCH#profit_dep_hf_}
          
          # Find corresponding Minor branch
          LATEST_MINOR_BRANCH="profit_dep_minor_$DATE_SUFFIX"

          echo "LATEST_HF_BRANCH=$LATEST_HF_BRANCH" >> $GITHUB_ENV
          echo "LATEST_MINOR_BRANCH=$LATEST_MINOR_BRANCH" >> $GITHUB_ENV

      - name: Verify Branch Existence
        id: check-branches
        run: |
          BRANCH_EXISTS=true
          if [[ -z "${{ env.LATEST_HF_BRANCH }}" || -z "${{ env.LATEST_MINOR_BRANCH }}" ]]; then
            echo "One or both branches do not exist."
            BRANCH_EXISTS=false
          else
            if ! git branch -r | grep -q "origin/${{ env.LATEST_HF_BRANCH }}"; then
              echo "HF branch '${{ env.LATEST_HF_BRANCH }}' does not exist."
              BRANCH_EXISTS=false
            fi
            if ! git branch -r | grep -q "origin/${{ env.LATEST_MINOR_BRANCH }}"; then
              echo "Minor branch '${{ env.LATEST_MINOR_BRANCH }}' does not exist."
              BRANCH_EXISTS=false
            fi
          fi
          
          echo "BRANCH_EXISTS=$BRANCH_EXISTS" >> $GITHUB_ENV

      - name: Create Pull Request for HF to Minor
        if: env.BRANCH_EXISTS == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating PR to merge ${{ env.LATEST_HF_BRANCH }} into ${{ env.LATEST_MINOR_BRANCH }}"
          gh pr create --base ${{ env.LATEST_MINOR_BRANCH }} --head ${{ env.LATEST_HF_BRANCH }} --title "Merge ${{ env.LATEST_HF_BRANCH }} into ${{ env.LATEST_MINOR_BRANCH }}" --body "Automated PR to merge ${{ env.LATEST_HF_BRANCH }} into ${{ env.LATEST_MINOR_BRANCH }}"

      - name: Handle Missing Branches
        if: env.BRANCH_EXISTS == 'false'
        run: |
          echo "Required branches are missing or not found."
          exit 1
