name: Auto Merge Branches

on:
  push:
    branches:
      - 'profit_dep_hf_*'
      - 'profit_dep_minor_*'

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Determine Target Branch
        id: determine-target
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          if [[ $branch_name == profit_dep_hf_* ]]; then
            target_branch="profit_dep_minor_${branch_name#profit_dep_hf_}"
          elif [[ $branch_name == profit_dep_minor_* ]]; then
            target_branch="master"
          else
            echo "No matching target branch found."
            exit 1
          fi
          echo "TARGET_BRANCH=$target_branch" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=$branch_name" >> $GITHUB_ENV
      - name: Check Branch Status
        id: check-status
        run: |
          git fetch origin
          source_commit=$(git rev-parse origin/${{ env.SOURCE_BRANCH }})
          target_commit=$(git rev-parse origin/${{ env.TARGET_BRANCH }})
          if [ "$source_commit" = "$target_commit" ]; then
            echo "Branches are up-to-date. No pull request needed."
            exit 0
          fi
      - name: Create Pull Request
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating PR to merge ${{ env.SOURCE_BRANCH }} into ${{ env.TARGET_BRANCH }}"
          gh pr create --base ${{ env.TARGET_BRANCH }} --head ${{ env.SOURCE_BRANCH }} --title "Merge ${{ env.SOURCE_BRANCH }} into ${{ env.TARGET_BRANCH }}" --body "Automated PR to merge ${{ env.SOURCE_BRANCH }} into ${{ env.TARGET_BRANCH }}"
