name: Resolve Branch Issues

on:
  workflow_dispatch:
  push:
    branches:
      - 'profit_dep_hf_*'
      - 'profit_dep_minor_*'

jobs:
  resolve-branch-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch All Remote Branches
        run: |
          git fetch --all

      - name: Verify Branch Existence
        id: check_branch
        run: |
          BRANCH_NAME="profit_dep_minor_09092024"
          REMOTE_BRANCH_EXISTS=$(git branch -r | grep -q "origin/$BRANCH_NAME" && echo "true" || echo "false")
          echo "REMOTE_BRANCH_EXISTS=$REMOTE_BRANCH_EXISTS" >> $GITHUB_ENV

      - name: Check Out Branch If It Exists
        if: env.REMOTE_BRANCH_EXISTS == 'true'
        run: |
          BRANCH_NAME="profit_dep_minor_09092024"
          if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
            echo "Branch '$BRANCH_NAME' is already checked out locally."
          else
            echo "Checking out branch '$BRANCH_NAME' from remote..."
            git checkout -b $BRANCH_NAME origin/$BRANCH_NAME
          fi

      - name: Handle Branch Not Found
        if: env.REMOTE_BRANCH_EXISTS == 'false'
        run: |
          echo "Branch 'profit_dep_minor_09092024' does not exist remotely."
          exit 1
