name: Auto Merge Branches

on:
  push:
    branches:
      - 'profit_dep_hf_*'
      - 'profit_dep_minor_*'

jobs:
  merge-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Create Pull Request for HF to Minor
        if: startsWith(github.ref, 'refs/heads/profit_dep_hf_')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          minor_branch="profit_dep_minor_${branch_name#profit_dep_hf_}"
          echo "Creating PR to merge $branch_name into $minor_branch"
          gh pr create --base $minor_branch --head $branch_name --title "Merge $branch_name into $minor_branch" --body "Automated PR to merge $branch_name into $minor_branch"
      - name: Create Pull Request for Minor to Master
        if: startsWith(github.ref, 'refs/heads/profit_dep_minor_')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Creating PR to merge $branch_name into master"
          gh pr create --base master --head $branch_name --title "Merge $branch_name into master" --body "Automated PR to merge $branch_name into master"
