name: Sync branches with conflict handling

on: 
  push:
    branches:
      - HF
      - minor

jobs: 
  branch-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name 'egangithub1502'
          git config --global user.email '2010177071b@gmail.com'

      # This step is only executed when HF is updated
      - name: Attempt to merge HF into minor
        if: github.ref == 'refs/heads/HF'
        id: merge_hf_to_minor
        run: |
          git fetch origin
          git checkout minor
          git merge origin/HF || git merge --abort

      - name: Handle conflict between HF and minor
        if: github.ref == 'refs/heads/HF' && failure()
        run: |
          git checkout -b temp/hf-to-minor-conflict
          git merge origin/HF
          git push origin temp/hf-to-minor-conflict
        continue-on-error: true

      # This step is executed when minor is updated or when HF is successfully merged into minor
      - name: Attempt to merge minor into master
        if: github.ref == 'refs/heads/minor' || (github.ref == 'refs/heads/HF' && success())
        id: merge_minor_to_master
        run: |
          git fetch origin
          git checkout master
          git merge origin/minor || git merge --abort

      - name: Handle conflict between minor and master
        if: (github.ref == 'refs/heads/minor' || (github.ref == 'refs/heads/HF' && success())) && failure()
        run: |
          git checkout -b temp/minor-to-master-conflict
          git merge origin/minor
          git push origin temp/minor-to-master-conflict
        continue-on-error: true
