name: Auto Merge

on:
  push:
    branches:
      - profit_dep_hf_*

jobs:
  merge:
    runs-on: ubuntu-22.04  # Specifies the runner image version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history for branches and tags

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.JEGANTOKEN1 }}" | gh auth login --with-token

      - name: Fetch All Branches
        run: |
          git fetch --all

      - name: Find and Merge Branches
        id: find-branches
        run: |
          # Find the latest branch matching the hf prefix
          HF_BRANCH=$(git branch -r | grep 'origin/profit_dep_hf_' | sort -V | tail -n 1 | sed 's|origin/||')
          MINOR_BRANCH=$(echo $HF_BRANCH | sed 's/hf_/minor_/')
          MASTER_BRANCH="master"

          echo "Latest HF branch: $HF_BRANCH"
          echo "Minor branch: $MINOR_BRANCH"
          echo "Master branch: $MASTER_BRANCH"

          # Check if branches exist
          if git show-ref --verify --quiet refs/heads/$MINOR_BRANCH; then
            echo "$MINOR_BRANCH exists"
          else
            echo "$MINOR_BRANCH does not exist"
            exit 1
          fi

          if git show-ref --verify --quiet refs/heads/$MASTER_BRANCH; then
            echo "$MASTER_BRANCH exists"
          else
            echo "$MASTER_BRANCH does not exist"
            exit 1
          fi

          # Merge hf branch into minor branch
          git checkout $MINOR_BRANCH
          git merge $HF_BRANCH --no-ff -m "Merge $HF_BRANCH into $MINOR_BRANCH"
          git push origin $MINOR_BRANCH

          # Merge minor branch into master branch
          git checkout $MASTER_BRANCH
          git merge $MINOR_BRANCH --no-ff -m "Merge $MINOR_BRANCH into $MASTER_BRANCH"
          git push origin $MASTER_BRANCH
