name: Auto Merge

on:
  push:
    branches:
      - profit_dep_hf_*

jobs:
  merge:
    runs-on: ubuntu-22.04  # Specifies the runner image version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history for branches and tags

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.JEGANTOKEN1 }}" | gh auth login --with-token

      - name: Fetch All Branches
        run: |
          git fetch --all
          git branch -r  # Debug: List all remote branches

      - name: Find and Merge Branches
        id: find-branches
        run: |
          # Find the latest branch matching the hf prefix
          HF_BRANCH=$(git branch -r | grep 'origin/profit_dep_hf_' | sort -V | tail -n 1 | sed 's|origin/||')
          echo "Latest HF branch: $HF_BRANCH"

          # Extract the date or unique identifier from HF_BRANCH
          DATE_SUFFIX=$(echo $HF_BRANCH | sed 's/profit_dep_hf_//')
          echo "Date suffix extracted: $DATE_SUFFIX"

          # Find the corresponding minor branch
          MINOR_BRANCH=$(git branch -r | grep "origin/profit_dep_minor_${DATE_SUFFIX}" | sed 's|origin/||')
          echo "Minor branch: $MINOR_BRANCH"
          echo "Master branch: master"

          # Check if branches exist
          if [ -z "$MINOR_BRANCH" ]; then
            echo "$MINOR_BRANCH does not exist"
            exit 1
          fi

          if git show-ref --verify --quiet refs/heads/master; then
            echo "Master branch exists"
          else
            echo "Master branch does not exist"
            exit 1
          fi

          # Merge hf branch into minor branch
          git checkout $MINOR_BRANCH
          git merge $HF_BRANCH --no-ff -m "Merge $HF_BRANCH into $MINOR_BRANCH"
          git push origin $MINOR_BRANCH

          # Merge minor branch into master branch
          git checkout master
          git merge $MINOR_BRANCH --no-ff -m "Merge $MINOR_BRANCH into master"
          git push origin master
