name: Auto Merge Branches

on:
  push:
    branches:
      - 'profit_dep_hf_*'

jobs:
  merge_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.JEGANTOKEN1 }}  # Use PAT for checkout

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config --global --add safe.directory /github/workspace

    - name: Find and merge branches
      run: |
        # Fetch all branches
        git fetch --all

        # Checkout the latest HF branch
        HF_BRANCH=$(git branch -r | grep "origin/profit_dep_hf_" | sort -r | head -n 1 | sed 's|origin/||')
        git checkout $HF_BRANCH

        # Perform the merge operation
        git merge origin/profit_dep_minor_08162024 || {
          echo "Conflict detected during merge from $HF_BRANCH to master";
          git checkout -b temp_branch_hf_minor
          git merge origin/profit_dep_minor_08162024
          git push origin temp_branch_hf_minor
          gh pr create --base master --head temp_branch_hf_minor --title "Resolve conflicts between $HF_BRANCH and master" --body "Conflicts detected. Please resolve conflicts."
          exit 1
        }

        # Push the changes
        git push origin $HF_BRANCH
