name: Auto Merge

on:
  push:
    branches:
      - profit_dep_hf_*

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.JEGANTOKEN1 }}

      - name: Find and merge branches
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Find the latest branch matching the hf prefix
          HF_BRANCH=$(git branch -r | grep 'origin/profit_dep_hf_' | sort -V | tail -n 1 | sed 's|origin/||')
          MINOR_BRANCH=$(echo $HF_BRANCH | sed 's/hf_/minor_/')
          MASTER_BRANCH="master"

          # Merge hf branch into minor branch
          git checkout $MINOR_BRANCH
          git merge $HF_BRANCH --no-ff
          git push origin $MINOR_BRANCH

          # Merge minor branch into master branch
          git checkout $MASTER_BRANCH
          git merge $MINOR_BRANCH --no-ff
          git push origin $MASTER_BRANCH
