name: Auto Merge

on:
  push:
    branches:
      - profit_dep_hf_*

jobs:
  merge:
    runs-on: ubuntu-22.04  # Specifies the runner image version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches all history for branches and tags

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch All Branches
        run: |
          git fetch --all

      - name: Find Latest Branches
        id: find-branches
        run: |
          # Find the latest branch matching the hf prefix
          HF_BRANCH=$(git branch -r | grep 'origin/profit_dep_hf_' | sort -V | tail -n 1 | sed 's|origin/||')
          MINOR_BRANCH=$(echo $HF_BRANCH | sed 's/hf_/minor_/')
          MASTER_BRANCH="master"

          echo "HF_BRANCH=$HF_BRANCH" >> $GITHUB_ENV
          echo "MINOR_BRANCH=$MINOR_BRANCH" >> $GITHUB_ENV
          echo "MASTER_BRANCH=$MASTER_BRANCH" >> $GITHUB_ENV

      - name: Check Branches Existence and Create if Needed
        run: |
          # Check if MINOR_BRANCH exists, create it if not
          if ! git show-ref --verify --quiet refs/heads/${{ env.MINOR_BRANCH }}; then
            echo "Branch ${{ env.MINOR_BRANCH }} does not exist. Creating it from ${{ env.MASTER_BRANCH }}."
            git checkout ${{ env.MASTER_BRANCH }}
            git checkout -b ${{ env.MINOR_BRANCH }}
            git push origin ${{ env.MINOR_BRANCH }}
          else
            echo "Branch ${{ env.MINOR_BRANCH }} exists."
          fi

      - name: Merge hf branch into minor branch
        run: |
          git checkout ${{ env.MINOR_BRANCH }}
          git merge ${{ env.HF_BRANCH }} --no-ff -m "Merge ${{ env.HF_BRANCH }} into ${{ env.MINOR_BRANCH }}"
          git push origin ${{ env.MINOR_BRANCH }}

      - name: Merge minor branch into master branch
        run: |
          git checkout ${{ env.MASTER_BRANCH }}
          git merge ${{ env.MINOR_BRANCH }} --no-ff -m "Merge ${{ env.MINOR_BRANCH }} into ${{ env.MASTER_BRANCH }}"
          git push origin ${{ env.MASTER_BRANCH }}
