name: Auto Merge Branches

on:
  push:
    branches:
      - 'profit_dep_hf_*'

jobs:
  find_and_merge_branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config --global --add safe.directory /github/workspace
    - name: Find latest HF and minor branches
      id: find_branches
      run: |
        # Find the latest HF branch
        HF_BRANCH=$(git branch -r | grep "origin/profit_dep_hf_" | sort -r | head -n 1 | sed 's|origin/||')
        echo "HF_BRANCH=$HF_BRANCH" >> $GITHUB_ENV
        # Find the latest minor branch
        MINOR_BRANCH=$(git branch -r | grep "origin/profit_dep_minor_" | sort -r | head -n 1 | sed 's|origin/||')
        echo "MINOR_BRANCH=$MINOR_BRANCH" >> $GITHUB_ENV
    - name: Merge HF into minor
      run: |
        git checkout ${{ env.MINOR_BRANCH }}
        git merge ${{ env.HF_BRANCH }} || {
          echo "Conflict detected during merge from ${{ env.HF_BRANCH }} to ${{ env.MINOR_BRANCH }}";
          git checkout -b temp_branch_hf_minor
          git merge ${{ env.HF_BRANCH }}
          echo "Creating pull request to resolve conflicts";
          gh pr create --base ${{ env.MINOR_BRANCH }} --head temp_branch_hf_minor --title "Resolve conflicts between ${{ env.HF_BRANCH }} and ${{ env.MINOR_BRANCH }}" --body "Conflicts detected. Please resolve conflicts."
          exit 1
        }
        git push origin ${{ env.MINOR_BRANCH }}
  merge_minor_to_master:
    needs: find_and_merge_branches
    runs-on: ubuntu-latest
    if: success() # Proceed only if the previous job succeeded

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch and checkout master branch
      run: |
        # Fetch all branches including master
        git fetch origin master:master
        # Checkout the master branch
        git checkout master
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config --global --add safe.directory /github/workspace
    - name: Merge minor into master
      run: |
        git merge ${{ env.MINOR_BRANCH }} || {
          echo "Conflict detected during merge from ${{ env.MINOR_BRANCH }} to master";
          git checkout -b temp_branch_minor_master
          git merge ${{ env.MINOR_BRANCH }}
          echo "Creating pull request to resolve conflicts";
          gh pr create --base master --head temp_branch_minor_master --title "Resolve conflicts between ${{ env.MINOR_BRANCH }} and master" --body "Conflicts detected. Please resolve conflicts."
          exit 1
        }
        git push origin master
